version: "3"

services:
  db:
    container_name: devlane_db
    image: mysql:5.6
    volumes:
      - ./docker/db/scripts/:/docker-entrypoint-initdb.d
      - localdevlanecl_dbdata-devlane:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_devlane_challenge
    ports:
      - "3306:3306"
  web:
    container_name: devlane_web
    depends_on:
      - db
    build:
      context: ./docker/web/.
    volumes:
      - ./src:/var/www/html
      - ./docker/web/apache/virtualhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/web/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"

  phpmyadmin:
    container_name: devlane_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
    # restart: always
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"

volumes:
  localdevlanecl_dbdata-devlane: 
  # redisinsight:
  # rabbitmqdata:
